enable_testing()
find_package(GTest QUIET)
#include_directories(${GTEST_INCLUDE_DIRS})
message("-- GTEST_FOUND: ${GTEST_FOUND} ${GTEST_BOTH_LIBRARIES}")

if (UNIX)
	set(LIB_EXTENSION so)
elseif (WIN32)
	set(LIB_EXTENSION lib)
endif ()

set(HEXTER_LIB ${CMAKE_SOURCE_DIR}/cmake-build-release/hexter.${LIB_EXTENSION})
if(EXISTS ${HEXTER_LIB})
	message("-- Found: hexter.${LIB_EXTENSION} ${HEXTER_LIB}")
else()
	set(HEXTER_LIB ${CMAKE_SOURCE_DIR}/cmake-build-debug/hexter.${LIB_EXTENSION})
	if(EXISTS ${HEXTER_LIB})
		message("-- Found: hexter.${LIB_EXTENSION} ${HEXTER_LIB}")
	else()
		message("-- Not Found: hexter.${LIB_EXTENSION} ${HEXTER_LIB}")
	endif()
endif()