enable_testing()
find_package(GTest QUIET)
#include_directories(${GTEST_INCLUDE_DIRS})
message("-- GTEST_FOUND: ${GTEST_FOUND} ${GTEST_BOTH_LIBRARIES}")

set(HEXTER_LIB ${CMAKE_SOURCE_DIR}/cmake-build-debug/hexter.lib)
if(EXISTS ${HEXTER_LIB})
	message("-- Found: hexter.lib ${HEXTER_LIB}")
else()
	message("-- Not Found: hexter.lib ${HEXTER_LIB}")
endif()