set(UTILS_FILES
	${CMAKE_CURRENT_SOURCE_DIR}/src/utils/common_fileio.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/utils/common_fileio.c
	${CMAKE_CURRENT_SOURCE_DIR}/src/utils/Helper.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/utils/Helper.c
	${CMAKE_CURRENT_SOURCE_DIR}/src/utils/Converter.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/utils/Converter.c
	)
set(HEXTER_FILES
	${CMAKE_CURRENT_SOURCE_DIR}/src/Globals.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/Printer.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/Printer.c
	${CMAKE_CURRENT_SOURCE_DIR}/src/Payloader.h
	${CMAKE_CURRENT_SOURCE_DIR}/src/Payloader.c
	)
